version: 2

sources:
  - name: aircraft_db
    database: RAW
    schema: PUBLIC
    tables:
      - name: AIRCRAFT
      - name: AIRLINES
      - name: AIRPORTS
      - name: FLIGHT_SUMMARY_DATA
      - name: INDIVIDUAL_FLIGHTS
